title: What’s up! This is Pingge Jiang!
description: Welcome to my personal website! I’m Pingge Jiang, a current PhD candidate in Computer Engineering at Drexel University, Philadelphia, PA, United States. I have more than five years research experience in image processing and related areas. This is my personal homepage. You can find my thoughts of life and research ideas.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
